### PR TITLE
Initial effort - OSD-3350

### PR DESCRIPTION
**Pull request by robotmaxtron**

### CODE REVIEW

**Comment by boranx** [comment]
lgtm

**Comment by lisa** [comment]
@robotmaxtron When you are ready to merge, `/unhold`.

/hold
/lgtm

**Comment by robotmaxtron** [comment]
@lisa Looks like merging is still blocked, does it need an approval from you as well?

**Review by lisa — APPROVED** [review]
/approve
/lgtm

I guess this repo needs an actual GitHub approval, and not just `/approve`.

**Pull request merged**
